{
 "title": "Ziggo modem info",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Instance",
    "query": {
     "query": "label_values(cable_modem_info, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Modem model",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cable_modem_info{instance=\"$Instance\"}",
     "legendFormat": "{{ model }}"
    }
   ]
  },
  {
   "title": "Software version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cable_modem_info{instance=\"$Instance\"}",
     "legendFormat": "{{ software_version }}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cable_modem_uptime_total{instance=\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Hardware version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cable_modem_info{instance=\"$Instance\"}",
     "legendFormat": "{{ hardware_version }}"
    }
   ]
  },
  {
   "title": "Device serial",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cable_modem_info{instance=\"$Instance\"}",
     "legendFormat": "{{ serial }}"
    }
   ]
  },
  {
   "title": "Docsis version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cable_modem_info{instance=\"$Instance\"}",
     "legendFormat": "{{ docsis_version }}"
    }
   ]
  },
  {
   "title": "Device mac address",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cable_modem_info{instance=\"$Instance\"}",
     "legendFormat": "{{ mac_address }}"
    }
   ]
  },
  {
   "title": "Downstream channels",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "cable_modem_downstream_channel_info{instance=\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Upstream channels",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "cable_modem_upstream_channel_info{instance=\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Downstream correctables",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(cable_modem_downstream_channel_correctables{instance=\"$Instance\"}[5m])",
     "legendFormat": "Channel {{ id }}"
    }
   ]
  },
  {
   "title": "Downstream uncorrectables",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(cable_modem_downstream_channel_uncorrectables{instance=\"$Instance\"}[5m])",
     "legendFormat": "Channel {{ id }}"
    }
   ]
  },
  {
   "title": "Downstream power",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "dBmV" }
   ],
   "targets": [
    {
     "expr": "cable_modem_downstream_channel_power{instance=\"$Instance\"} / 10",
     "legendFormat": "Channel {{ id }}"
    }
   ]
  },
  {
   "title": "Downstream SNR",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "expr": "cable_modem_downstream_channel_snr{instance=\"$Instance\"} / 10",
     "legendFormat": "Channel {{ id }}"
    }
   ]
  },
  {
   "title": "Upstream power",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "dBmV" }
   ],
   "targets": [
    {
     "expr": "cable_modem_upstream_channel_power{instance=\"$Instance\"} / 10",
     "legendFormat": "Channel {{ id }}"
    }
   ]
  },
  {
   "title": "Modem temperature",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "cable_modem_temperature_c{instance=\"$Instance\"}",
     "legendFormat": "Channel {{ id }}"
    }
   ]
  }
 ]
}